project:
  type: website
  output-dir: _site
website:
  title: "Ran Li"
  
  site-url: "https://ranli.dev"
  google-analytics: "G-PC0JG3M1ZX"
  navbar:
    logo-href: index.qmd
    left:
      - text: "Home"
        href: index.qmd
      - text: "Blog"
        href: blog.qmd
      - text: "Portfolio"
        href: portfolio.qmd      
      - text: "Resume"
        href: resume.pdf 
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/ran-li-6b722718/
        target: _blank
      - icon: github
        href: https://github.com/ran-codes
        target: _blank
      - text: "{{< iconify fa6-brands:bluesky >}}"
        href: https://bsky.app/profile/ran-li.bsky.social
        target: _blank
      - icon: twitter
        href: https://x.com/ran_codes      
        target: _blank
      - icon: medium
        href: https://medium.com/@ranli2011
        target: _blank
format:
  html:
    theme: cosmo
    css: styles.css